apiVersion: v1
kind: Pod
metadata:
  name: javapod
  labels: 
    app: helloworld
    env: dev
spec:
  containers:
    - name: javapod
      image: pratikmittal/java-repo
      ports:
        - name: javaport
          containerPort: 3000
